/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { ScrollView, StyleSheet, Text } from 'react-native';
import KinasticHealthKit from './App/Model/HealthKit/KinasticHealthKit';
import HKObjectTypes from './App/Model/HealthKit/HKObjectType';
import HKQuery from './App/Model/HealthKit/HKQuery';
import HKSampleQuery from './App/Model/HealthKit/HKSampleQuery';
import { HKObjectSampleType } from './App/Model/HealthKit';
import { HKWorkoutActivityType } from './App/Model/HealthKit';

export class App extends Component<{}> {
  state = {
    status: 'starting',
    message: '--',
  };

  componentDidMount() {
    // console.log(JSON.stringify(HKObjectTypes, null, 4));
    KinasticHealthKit.requestAuthorization(HKObjectTypes, HKObjectTypes).then((result: any) => {
      this.read();
    });
  }

  async read() {
    await KinasticHealthKit.querySample(
      new HKSampleQuery(
        HKObjectSampleType.workout,
        HKQuery.predicateForWorkouts(HKWorkoutActivityType.traditionalStrengthTraining),
      ),
    ).then(async results => {
      // console.log(JSON.stringify(results, null, 4));
      const first = results[results.length - 1];
      console.log(JSON.stringify(first, null, 4));
      if (first) {
        // KinasticHealthKit.queryWorkoutRoute(first.uuid).then((result: CLLocation[]) => {
        //   console.log(JSON.stringify(result, null, 4));
        // });
      }
      // console.log(JSON.stringify(results, null, 4));
    });
    // const HKMetadataKeyExternalUUID = 'HKExternalUUID';
    // await KinasticHealthKit.querySample(
    //   new HKSampleQuery(
    //     HKQuantityType.dietaryCalcium,
    //     HKQuery.predicateForQuantitySamples(NSComparisonPredicateOperator.gte, 70, 'mg'),
    //   ),
    // ).then(results => {
    //   console.log('------------------------------------');
    //   console.log(JSON.stringify(results, null, 4));
    //   console.log('------------------------------------');
    // });

    // await KinasticHealthKit.querySample(
    //   new HKSampleQuery(
    //     HKQuantityType.dietaryCalcium,
    //     HKQuery.predicateForObjects(
    //       undefined,
    //       undefined,
    //       undefined,
    //       undefined,
    //       undefined,
    //       'Meal',
    //       NSComparisonPredicateOperator.eq,
    //       'Dinner',
    //     ),
    //   ),
    // ).then(results => {
    //   console.log('------------------------------------');
    //   console.log(JSON.stringify(results, null, 4));
    //   console.log('------------------------------------');
    // });

    // await KinasticHealthKit.queryCorrelation(
    //     new HKCorrelationQuery(HKCorrelationType.food, undefined, {
    //       [HKQuantityType.dietaryEnergyConsumed]: HKQuery.predicateForQuantitySamples(
    //           NSComparisonPredicateOperator.gte,
    //           10,
    //           'kcal',
    //       ),
    //     }),
    // ).then(results => {
    //   console.log('------------------------------------');
    //   console.log(JSON.stringify(results, null, 4));
    //   console.log('------------------------------------');
    // });

    // await KinasticHealthKit.queryCorrelation(
    //   new HKCorrelationQuery(
    //     HKCorrelationType.food,
    //     HKQuery.predicateForSamples(
    //       moment()
    //         .subtract(2, 'weeks')
    //         .toDate(),
    //     ),
    //   ),
    // ).then(results => {
    //   console.log('------------------------------------');
    //   console.log(JSON.stringify(results, null, 4));
    //   console.log('------------------------------------');
    // });
    //
    // await KinasticHealthKit.saveWorkout([
    //   HKWorkout.build(
    //       '7d7761c5-31bd-4178-b0ec-8b94138999e4',
    //       HKWorkoutActivityType.traditionalStrengthTraining,
    //       moment()
    //           .subtract(1, 'days')
    //           .toDate(),
    //       moment()
    //           .subtract(1, 'days')
    //           .add(1, 'hour')
    //           .toDate(),
    //       1024,
    //   ),
    // ]);

    // const foodDate = moment()
    //   .subtract(1, 'days')
    //   .toDate();
    //
    // const foodId = 'foodId2';
    //
    // await KinasticHealthKit.saveCorrelation([
    //   HKCorrelation.build(foodId, HKCorrelationType.food, foodDate, foodDate, [
    //     HKQuantitySample.build(foodId, HKQuantityType.dietaryCarbohydrates, foodDate, foodDate, 30),
    //     HKQuantitySample.build(foodId, HKQuantityType.dietaryFatTotal, foodDate, foodDate, 15),
    //     HKQuantitySample.build(foodId, HKQuantityType.dietaryProtein, foodDate, foodDate, 25),
    //   ]),
    // ]);
  }

  render() {
    return (
      <ScrollView style={styles.container}>
        <Text style={styles.welcome}>☆KinasticHealthkit example☆</Text>
        <Text style={styles.instructions}>STATUS: {this.state.status}</Text>
      </ScrollView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
