export class HKUnit {
    static determineUnit(type) {
        switch (type) {
            case 'appleExerciseTime':
                return 'min';
            case 'appleStandTime':
                return 'min';
            case 'pushCount':
                return 'count';
            case 'swimmingStrokeCount':
                return 'count';
            case 'distanceSwimming':
                return 'm';
            case 'distanceWheelchair':
                return 'm';
            case 'heartRateVariabilitySDNN':
                return 'ms';
            case 'insulinDelivery':
                return 'IU';
            case 'restingHeartRate':
                return 'count/min';
            case 'vo2Max':
                return 'ml/kg*minute';
            case 'waistCircumference':
                return 'cm';
            case 'walkingHeartRateAverage':
                return 'count/min';
            case 'distanceDownhillSnowSports':
                return 'm';
            case 'activeEnergyBurned':
                return 'kcal';
            case 'environmentalAudioExposure':
                return 'dBHL';
            case 'headphoneAudioExposure':
                return 'dBHL';
            case 'basalBodyTemperature':
                return 'degC';
            case 'basalEnergyBurned':
                return 'kcal';
            case 'bloodAlcoholContent':
                return '%';
            case 'bloodGlucose':
                return 'mmg/dL';
            case 'bloodPressureDiastolic':
                return 'mmHg';
            case 'bloodPressureSystolic':
                return 'mmHg';
            case 'bodyFatPercentage':
                return '%';
            case 'bodyMass':
                return 'kg';
            case 'bodyMassIndex':
                return 'kg'; // TODO might be wrong
            case 'bodyTemperature':
                return 'degC';
            case 'dietaryBiotin':
                return 'mg';
            case 'dietaryCaffeine':
                return 'mg';
            case 'dietaryCalcium':
                return 'mg';
            case 'dietaryCarbohydrates':
                return 'mg';
            case 'dietaryChloride':
                return 'mg';
            case 'dietaryCholesterol':
                return 'mg';
            case 'dietaryChromium':
                return 'mg';
            case 'dietaryCopper':
                return 'mg';
            case 'dietaryEnergyConsumed':
                return 'kcal';
            case 'dietaryFatMonounsaturated':
                return 'g';
            case 'dietaryFatPolyunsaturated':
                return 'g';
            case 'dietaryFatSaturated':
                return 'g';
            case 'dietaryFatTotal':
                return 'g';
            case 'dietaryFiber':
                return 'g';
            case 'dietaryFolate':
                return 'mg';
            case 'dietaryIodine':
                return 'mg';
            case 'dietaryIron':
                return 'mg';
            case 'dietaryMagnesium':
                return 'mg';
            case 'dietaryManganese':
                return 'mg';
            case 'dietaryMolybdenum':
                return 'mg';
            case 'dietaryNiacin':
                return 'mg';
            case 'dietaryPantothenicAcid':
                return 'mg';
            case 'dietaryPhosphorus':
                return 'mg';
            case 'dietaryPotassium':
                return 'mg';
            case 'dietaryProtein':
                return 'g';
            case 'dietaryRiboflavin':
                return 'mg';
            case 'dietarySelenium':
                return 'mg';
            case 'dietarySodium':
                return 'mg';
            case 'dietarySugar':
                return 'g';
            case 'dietaryThiamin':
                return 'mg';
            case 'dietaryVitaminA':
                return 'mg';
            case 'dietaryVitaminB6':
                return 'mg';
            case 'dietaryVitaminB12':
                return 'mg';
            case 'dietaryVitaminC':
                return 'mg';
            case 'dietaryVitaminD':
                return 'mg';
            case 'dietaryVitaminE':
                return 'mg';
            case 'dietaryVitaminK':
                return 'mg';
            case 'dietaryWater':
                return 'L';
            case 'dietaryZinc':
                return 'mg';
            case 'distanceCycling':
                return 'm';
            case 'distanceWalkingRunning':
                return 'm';
            case 'electrodermalActivity':
                return 'S';
            case 'flightsClimbed':
                return 'count';
            case 'forcedExpiratoryVolume1':
                return 'L';
            case 'forcedVitalCapacity':
                return 'L';
            case 'heartRate':
                return 'count/min';
            case 'height':
                return 'm';
            case 'inhalerUsage':
                return 'count';
            case 'leanBodyMass':
                return 'kg';
            case 'nikeFuel':
                return 'count';
            case 'numberOfTimesFallen':
                return 'count';
            case 'oxygenSaturation':
                return '%';
            case 'peakExpiratoryFlowRate':
                return 'L/min';
            case 'peripheralPerfusionIndex':
                return '%';
            case 'respiratoryRate':
                return 'count/min';
            case 'stepCount':
                return 'count';
            case 'uvExposure':
                return 'count';
            default:
                return undefined;
        }
    }
}
//# sourceMappingURL=HKUnit.js.map