"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var NSComparisonPredicateOperator;
(function (NSComparisonPredicateOperator) {
    NSComparisonPredicateOperator["beginsWith"] = "beginsWith";
    NSComparisonPredicateOperator["between"] = "between";
    NSComparisonPredicateOperator["contains"] = "contains";
    NSComparisonPredicateOperator["customSelector"] = "customSelector";
    NSComparisonPredicateOperator["endsWith"] = "endsWith";
    NSComparisonPredicateOperator["equalTo"] = "eq";
    NSComparisonPredicateOperator["eq"] = "eq";
    NSComparisonPredicateOperator["greaterThan"] = "gt";
    NSComparisonPredicateOperator["gt"] = "gt";
    NSComparisonPredicateOperator["greaterThanOrEqualTo"] = "gte";
    NSComparisonPredicateOperator["gte"] = "gte";
    NSComparisonPredicateOperator["in"] = "in";
    NSComparisonPredicateOperator["lessThan"] = "lt";
    NSComparisonPredicateOperator["lt"] = "lt";
    NSComparisonPredicateOperator["lessThanOrEqualTo"] = "lte";
    NSComparisonPredicateOperator["lte"] = "lte";
    NSComparisonPredicateOperator["like"] = "like";
    NSComparisonPredicateOperator["matches"] = "matches";
    NSComparisonPredicateOperator["notEqualTo"] = "notEqualTo";
})(NSComparisonPredicateOperator = exports.NSComparisonPredicateOperator || (exports.NSComparisonPredicateOperator = {}));
