import { NSPredicateType } from './NSPredicateType';
import { NSComparisonPredicateOperator } from './NSComparisonPredicateOperator {';
import { HKSource, HKSourceJson } from './HKSource';
import { HKWorkout, HKWorkoutJson } from './HKWorkout';
import { HKDevice, HKDeviceJson } from './HKDevice';
import { HKSourceRevision, HKSourceRevisionJson } from './HKSourceRevision';
import { HKQueryOptions } from './HKQueryOptions';
import { HKFHIRResourceType } from './HKFHIRResourceType';
import { HKWorkoutActivityType } from './HKWorkoutActivityType';
export declare type NSPredicateJson = {
    type: NSPredicateType;
    operator?: NSComparisonPredicateOperator;
    value?: number;
    fhirResourceType?: HKFHIRResourceType;
    source?: HKSourceJson;
    identifier?: string;
    uuid?: string;
    workout?: HKWorkoutJson;
    device?: HKDeviceJson[];
    sourceRevisions?: HKSourceRevisionJson[];
    uuids?: string[];
    deviceProperty?: string;
    allowedValues?: string[];
    metadataKey?: string[];
    unit?: string;
    startDate?: string;
    endDate?: string;
    options?: HKQueryOptions;
    activityType?: HKWorkoutActivityType;
    duration?: number;
    totalDistance?: number;
    totalEnergyBurned?: number;
    totalSwimmingStrokeCount?: number;
    totalFlightsClimbed?: number;
};
export declare class NSPredicate {
    type: NSPredicateType;
    operator?: NSComparisonPredicateOperator;
    value?: number;
    fhirResourceType?: HKFHIRResourceType;
    source?: HKSource;
    identifier?: string;
    uuid?: string;
    workout?: HKWorkout;
    device?: HKDevice[];
    sourceRevisions?: HKSourceRevision[];
    uuids?: string[];
    deviceProperty?: string;
    allowedValues?: string[];
    metadataKey?: string[];
    unit?: string;
    startDate?: Date;
    endDate?: Date;
    options?: HKQueryOptions;
    activityType?: HKWorkoutActivityType;
    duration?: number;
    totalDistance?: number;
    totalEnergyBurned?: number;
    totalSwimmingStrokeCount?: number;
    totalFlightsClimbed?: number;
    constructor(json?: Partial<NSPredicateJson>);
    toJS(): NSPredicateJson;
}
